### ISSUE TITLE
Bitsvib scientific topics not all showing up

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#261]
The BITSVIB materials all have scientific_topics (as 'schema:genre' in the scraper). They're not all being found despite being valid edam ontology terms.

e.g. https://tess.elixir-uk.org/materials/data-carpentry-workshop-data-management-beyond-excel

has no scientific topics but the page has 4 terms: Data managment, Data handling, Data visualisation, Data quality managment
https://www.bits.vib.be/training-overview/data-carpentry-workshop

which are in edam (see data visualization): https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Ftopic_0092&jump_to_nav=true

**Comment by knirirr** [comment]
It all seems to be working on the scraper side; the scraper is picking up these terms and passing them on to the API client gem, which in turn posts them to the server where they are received. 

Within the Rails console, ` ScientificTopic.find_by_preferred_label("Data visualisation")` is pulling out a hit so that value is present. I'm also seeing scientific topics created for various entries, e.g. /materials/introduction-to-gene-regulation, so that part is working as well. 

Yet, as you say, some of these terms aren't added to the relevant records. Most odd.
