### ISSUE TITLE
Event datetime needs fixing up

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#375]
Add timezone when event is online. There is no location to infer timezone so will need to add a field.
The default end time should be plus an hour for online events and 5pm the same day for face-to-face events. The default start time should be 9am.

**Comment by knirirr** [comment]
I've done some of this, but I'm not sure of a good way to guess the timezone. Do you have any thoughts on that?

**Comment by knirirr** [comment]
Concerning the timezone, it seems that the start and end times for an event are this class of object:

http://api.rubyonrails.org/classes/ActiveSupport/TimeWithZone.html

...which, it would appear, converts input into UTC when parsed:

    >> Time.zone.parse('2016-11-20 21:00:00 EST')
    => Mon, 21 Nov 2016 02:00:00 UTC +00:00
    >> e.end = '2016-11-20 21:00:00 EST'
    => "2016-11-20 21:00:00 EST"
    >> e.end.zone
    => "UTC"
    >> e.end
    => Mon, 21 Nov 2016 02:00:00 UTC +00:00

Would it perhaps make sense to put the timezone in the content provider? Then, it could be accessed in events.rb by means of `self.content_provider.timezone` if not nil and applied to the start and end times?

**Comment by njall** [comment]
I don't think so. The content provider could have events from lots of different timezones. For example, Software Carpentry is a CP but locations of workshops are all over the world. The timezone specification will need to stay with the idividual events

**Comment by knirirr** [comment]
No problem; I'm proceeding with adding that. Apologies for the nuisance but I do have one other question, though. Scrapers can parse this field out and add it but I've had to add a separate field so users can add it manually. If we supply a list of timezones for the user then there are so many that it ought really to autocomplete; a dropdown will be too long.

I note that there's an autocomplete template here:

https://github.com/ElixirUK/TeSS/blob/master/app/views/common/_autocompleter.html.erb

That appears to be using existing models, e.g. /materials.json whereas I'm after a much simpler URL which can supply the list of timezones only, e.g. https://biosharing.org/content/domains

Is there any objection if I add such a thing? I don't see any existing controller so if I'm correct I'd probably have to add one. Or, I could simply leave timezone as a plain text field given that most updates will be via scrapers. 

As mentioned in a previous comment, if the supplied timezone string is appended to the date and time within the scrapers then ActiveSupport::TimeWithZone should parse it. The Software Carpentry pages seem to put a timezone only after the end time so that would need to be parsed out separately and added to the start and end time strings before allowing the Event model to parse them.

**Comment by knirirr** [comment]
Does anything else need to be done with this, or should I close it?
