### ISSUE TITLE
Allow users to suggest values for missing attributes

### ISSUE THREAD

**Issue by njall** [ElixirTeSS/TeSS#381]
Any logged in user should be given a text box whereever there is a nil value for a resource attribute. The submitted value should be kept in a queue until a curator approves it. 

For example, an event will go from:
Venue: nil 

to:
Venue: Where is this event taking place? [submit ](http://link_to_form.com)

**Comment by fbacall** [comment]
I had a look at your branch @knirirr 

I wonder if instead of having to list the types of each suggestible attribute (https://github.com/ElixirTeSS/TeSS/commit/d8deeb347c834c63a81740aa02201c0dc33cc7c6#diff-ec6f34b88284e08a2196b3e24ef0567eR12) we could re-use the the code in the `_form.html.erb` partial, but just have it submit to a different URL?

You could extract out all the form fields into another partial, then include it in both `_form` and `_suggest_edits`.

Also the `missing_fields?` check is probably unnecessary. Even if all fields are present, a user may want to make suggestions/changes.

**Comment by knirirr** [comment]
Indeed, changes like that could be made. I may perhaps get chance next week. 
Is the general UX/UI acceptable, though? There didn't seem to be any firm opinion on how this feature should look to the user, so I am keen to know this before I proceed with refactoring.

**Comment by fbacall** [comment]
Looks fine to me, but I can't say I really have a good eye for UX, and won't be the one using it.

**Comment by knirirr** [comment]
Thanks. In that case, unless @njall has any comments I'll have to proceed along those lines and hope it turns out to be acceptable.

**Comment by knirirr** [comment]
What's the status of this one?

**Comment by njall** [comment]
Review status and embed within suggestion framework https://github.com/ElixirTeSS/TeSS/issues/381
